export const filters = [
  { value: "Java", label: "Java" },
  { value: "React", label: "React" },
  { value: "Redux", label: "Redux" },
  { value: "React Native", label: "React Native" },
  { value: "Swift", label: "Swift" },
  { value: "Typescript", label: "Typescript" },
  { value: "Javascript", label: "Javascript" },
  { value: "CRUD", label: "CRUD" },
  { value: "Flutter", label: "Flutter" },
  { value: "Template", label: "Template" },
  { value: "Go", label: "Go" },
  { value: "Nextjs", label: "Nextjs" },
  { value: "Remix", label: "Remix" },
  { value: "Express", label: "Express" },
  { value: "Fastify", label: "Fastify" },
  { value: "Nestjs", label: "Nestjs" },
  { value: "Mobile", label: "Mobile" },
];
